# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /
    controller: App\Controller\LuckyController::number

form_formation :
    path :  /formation/create
    
form_formation_edit:
    path :  /formation/edit/{id}
    controller: App\Controller\formationController::edit

valid_formation:
    path :  /formation/edit/{id}
    controller: App\Controller\formationController::edit
    
    
    
    